project:
  type: website

website:
  title: "**Blog** | Teun van den Brand"
  site-url: https://teunbrand.github.io/teunbrand_blog/
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: spacelab
    css: styles.css



